//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10._01._2018_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int id { get; set; }
        public int booking_code { get; set; }
        public System.DateTime check_in_date { get; set; }
        public System.DateTime check_out_date { get; set; }
        public int adult_count { get; set; }
        public Nullable<int> child_count { get; set; }
        public int room_type_id { get; set; }
        public int user_id { get; set; }
        public bool booking_status { get; set; }
    
        public virtual Room_Types Room_Types { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
