//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10._01._2018_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int id { get; set; }
        public string employer_full_name { get; set; }
        public string employer_info { get; set; }
        public System.DateTime employer_start_time { get; set; }
        public System.DateTime employer_end_time { get; set; }
        public double employer_salary { get; set; }
        public int employer_type_id { get; set; }
    
        public virtual Employer_Types Employer_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
