//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10._01._2018_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expence
    {
        public int id { get; set; }
        public int expence_type_id { get; set; }
        public string expence_description { get; set; }
        public double expence_amount { get; set; }
        public int payment_id { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Expences_Types Expences_Types { get; set; }
    }
}
