//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10._01._2018_Hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Employer_Types> Employer_Types { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Expence> Expences { get; set; }
        public virtual DbSet<Expences_Types> Expences_Types { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Payment_Types> Payment_Types { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Room_Details> Room_Details { get; set; }
        public virtual DbSet<Room_Types> Room_Types { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Rooms_Details> Rooms_Details { get; set; }
        public virtual DbSet<Rooms_Guests> Rooms_Guests { get; set; }
        public virtual DbSet<Rooms_Photos> Rooms_Photos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
