//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10._01._2018_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms_Photos
    {
        public int Id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> photo_id { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Room Room { get; set; }
    }
}
