//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10._01._2018_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public int employer_id { get; set; }
        public string task_description { get; set; }
        public System.DateTime task_start_time { get; set; }
        public System.DateTime task_end_time { get; set; }
        public bool task_status { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
